# Generated by Django 4.1.3 on 2023-01-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='tags_in_task', to='task.tag'),
        ),
    ]
