# Generated by Django 4.1.3 on 2023-02-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('#FF0000', 'Red'), ('#FFA500', 'Orange'), ('#FFFF00', 'Yellow'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#000000', 'Black'), ('#FFFFFF', 'White'), ('#808080', 'Gray'), ('#A52A2A', 'Brown'), ('#F5F5DC', 'Beige'), ('#40E0D0', 'Turquoise'), ('#00FFFF', 'Cyan'), ('#FF00FF', 'Magenta'), ('#E6E6FA', 'Lavender'), ('#800000', 'Maroon'), ('#808000', 'Olive'), ('#008080', 'Teal')], default='#00FF00', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='tags_in_task', to='task.tag'),
        ),
    ]
