# Generated by Django 4.1.3 on 2023-02-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_tag_color_alter_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imagen_profile',
            field=models.ImageField(blank='', default='', upload_to='profile/'),
        ),
    ]
