# Generated by Django 4.1.6 on 2023-02-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_imagen_task_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='tags_in_task', to='task.tag'),
        ),
    ]
